travis:
  secure:
    BINSTAR_TOKEN: r5AY16dJLr2rMC3oeHlofTJP/FvS3iwB8pgvJJK+cXpg2kD+tnyx3UqiKhk4DtXBDtKoPvd2ryvZ5gnfqWu1/XoIScMuVV8nqFdKqz60+bS14tkGPIaO0VxPkUkB8bdcAYizZkch0bMwmF+Zx4LudWb8NLXeYDgMHa/DAaRrai06wQK3oo1OoTcWNUsPUG6XOy7BU0Qh2lpxi/aL57/RWoamufmTlrkFXqAKdhJLJ91081UsSK7gIIVTpyh65jBpSoaBwdIbG0J/JHpnXWiu4Zo//RAlOWi0002cN6DbvrFy8CdB648jFDRPWnoRA6y0KNWELe4DALxiHc53fNDABHBpc5eysoHH9/qSy0oMMP+p7XeQXas18T3ICFfqQxaQu+JTXzyOFOt5zjGXflY1wJOCpF544SoxOgC7qwPMmaY4cVSr9RpNapG78HB1BtDCCZfLLx8QXZAhxOx2Kgpaoaou4ZZ0auj4eVXYfxrzPb+s/ajQy9Bs8oOzoaIyTxbea7MnGxMujbmBy2Q2ESXGqbKsAgli6bpM6jhXjLIEEu9rraDtklsa1nw6EWtzuT1TBLgFWRZ2XlyUHdjyaFz/dozQiafjw3ZyImZH8HQj7+fA1bF04YWMbfg88GFBUzOmSCexDdtz4uoCf8usC+7lihfMv+t659cycZSCodqWfM0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
